name: Run Tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Environment'
        uses: ./.github/actions/setup-test-environment

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Run Unit Tests'
        run: pnpm test:unit

  run_e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Environment'
        uses: ./.github/actions/setup-test-environment

      - name: 'Install Dependencies'
        run: pnpm install

      - name: 'Install Playwright'
        run: pnpm playwright install --with-deps

      - name: 'Run e2e Tests'
        run: pnpm test:e2e
