name: Run Tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  call_setup_test_env:
    uses: ./.github/workflows/_setup-test-env.yaml

  run_unit_tests:
    needs: call_setup_test_env
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - run: pnpm install
      - run: pnpm test:unit

  run_e2e_tests:
    needs: call_setup_test_env
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - run: pnpm install
      - run: pnpm playwright install --with-deps
      - run: pnpm test:integration
